### ISSUE TITLE
Docker container user

### ISSUE THREAD

**Issue by ralfw85** [jgraph/docker-drawio#97] opened 2022-11-13 09:33 UTC
The web-app is running under the root user in the docker container. (run "ps faux" inside to see it)
It is bad to run a web-app as root. Please create an own user with specific rights for more security. :)

**Comment by m-mohamedin** [comment] 2022-11-15 17:12
Will be available in the next release (Duplicate of #36)

**Closed as completed by m-mohamedin** 2022-11-15 17:12 UTC
