### ISSUE TITLE
Is it possible to have personal 'viewer.diagrams.net' ?

### ISSUE THREAD

**Issue by rootnoir** [jgraph/docker-drawio#23] opened 2021-03-03 14:12 UTC
Hi! We use docker-drawio in local network, and it's work greate! 
But we need viewer.diagrams.net functional.. and seems there is no docker image for it..

Is it possible to have personal 'viewer.diagrams.net' ?

**Comment by davidjgraph** [comment] 2021-03-03 16:52
viewer.diagrams.net maps to exactly the same code as app.diagrams.net.

**Comment by rootnoir** [comment] 2021-03-03 17:52
> viewer.diagrams.net maps to exactly the same code as app.diagrams.net.

shure, but how to get it in container? i can't find any settings, to make viewer from app ) 
it should always use lightbox=1 i guess..

**Comment by davidjgraph** [comment] 2021-03-03 17:53
Probably, yes, but then this is a duplicate of your other issue.

**Comment by rootnoir** [comment] 2021-03-03 17:57
> Probably, yes, but then this is a duplicate of your other issue.

yes.. when we get a solution, i'll close both )

**Closed** 2021-03-03 17:58 UTC

**Comment by rootnoir** [comment] 2021-03-04 10:17
Solution: https://github.com/jgraph/drawio/issues/1855#issuecomment-790499581
