### ISSUE TITLE
Receiving Malformed URI error on startup

### ISSUE THREAD

**Issue by factor3** [jgraph/docker-drawio#125] opened 2023-10-10 19:12 UTC
Running the drawio container on an Almalinux distro, I am seeing no errors in the logs, The container starts up without problems.

When attempting to access the web page, however, I first get the "Loading" page for a second, but then I get a message box witg the following message:

Failed to execute 'open' on 'XMLHttpRequest': Invalid URL

This is on Chrome. On Firefox the message varies a little:

The URI is malformed.

When clicking on the message box's Ok button, I get the page shown in the attached file:
![dwawproblem](https://github.com/jgraph/docker-drawio/assets/138332567/84a3fa95-3c06-4d7b-8b2f-665fdabde4bb)

This page does not provide any drawing capabilities.

This looks like a Javascript problem. Is there any way to make this application work properly?

**Comment by donprosko** [comment] 2023-10-10 21:00
same to me also with jgraph/drawio:22.0.3
jgraph/drawio:21.7.5 seems OK w/o that error

**Comment by factor3** [comment] 2023-10-10 21:43
I went back to V21.7.5 and so far the startup is behaving properly.

Thanks for the heads- up. It looks like the latest has a bug that needs fixing...

**Comment by microbearlogist** [comment] 2023-10-19 15:41
Same here, but only with Firefox (Desktop and Android) and not on all my machines.

My netbook and smartphone got he "The URl is malformed" message and the interface crash like the example screenshot.
But not my Desktop computer (tested on a fresh installation of Firefox).

Chrome, Vivaldi and Edge are working fine on every machine.

21.7.5 solve the issue.


I've got nothing in my docker logs or in my Firefox console. Any clues?

**Comment by jeffreyswiggins** [comment] 2023-10-22 20:47
I am getting this same issue and have been for several weeks on the latest branch and I can confirm that reverting to [v21.7.5](https://github.com/jgraph/docker-drawio/releases/tag/v21.7.5) fixes the problem.

**Comment by factor3** [comment] 2023-10-23 15:12
Yes, that is what I did and have been happily using Draw.io since.
 
   Thanks for the confirmation.

**Comment by microbearlogist** [comment] 2023-10-24 09:38
The bug appears with 22.0.0.
v21.8.2 also works fine.

Edit:
Ok, figured out:

This is due to this [commit](https://github.com/jgraph/docker-drawio/commit/2d6f60db48561758d7749aa79357ccbbde789abd#diff-9ee9dc1cf59bb73d776f2fc62dcf209d80a33c4ca1ab2f61ea3b5ceca4bde89e)

Now you need to specify the variable "DRAWIO_SERVER_URL" in your docker-compose.yml environment.
See https://github.com/jgraph/docker-drawio/tree/dev/self-contained

**Comment by m-mohamedin** [comment] 2023-10-25 01:39
Will be fixed in the next release.
Thanks @microbearlogist for pointing to the source of the problem

**Closed as completed by m-mohamedin** 2023-10-25 01:39 UTC
