### ISSUE TITLE
Improperly generated `export to URL` for Lightbox viewer enabled for self hosted docker image (refs to #12)

### ISSUE THREAD

**Issue by tafkos** [jgraph/docker-drawio#20] opened 2021-01-12 08:11 UTC
### This bug have two reasons to be fixed:
1) Missed  `DRAWIO_LIGHTBOX_URL` docker parameter to propagate to `$CATALINA_HOME/webapps/draw/js/PreConfig.js` in both [alpine/docker-entrypoint.sh#L33](https://github.com/jgraph/docker-drawio/blob/master/alpine/docker-entrypoint.sh#L33) and [debian/docker-entrypoint.sh#L33](https://github.com/jgraph/docker-drawio/blob/master/debian/docker-entrypoint.sh#L33)
```diff
#DRAWIO_VIEWER_URL is path to the viewer js, e.g. https://www.example.com/js/viewer.min.js
echo "window.DRAWIO_VIEWER_URL = '${DRAWIO_VIEWER_URL}';" >> $CATALINA_HOME/webapps/draw/js/PreConfig.js
+echo "window.DRAWIO_LIGHTBOX_URL = '${DRAWIO_LIGHTBOX_URL}';" >> $CATALINA_HOME/webapps/draw/js/PreConfig.js
echo "window.DRAW_MATH_URL = 'math';" >> $CATALINA_HOME/webapps/draw/js/PreConfig.js
```
2)  URL link is not properly generated when doing File-->Export to-->URL. Currently this link opens file in editor even if **lightbox** tick is chosen on URL creation dialog.  Need to manually edit generated URL by adding **lightbox=1&**.   
Seems to me this bug should be fixed in [main drawio codebase](https://github.com/jgraph/drawio), not in docker. But as described below in workaround of #12 need to add how to properly specify `DRAWIO_LIGHTBOX_URL` in docker-compose variable to use self-hosted lightbox viewer.

### As workaround to fix #12 w/o rebuilding docker image:
1. Clone project, and modify self-contained/docker-compose.yml file as described in [self-contained/README](https://github.com/jgraph/docker-drawio/tree/master/self-contained#configuration)
```shell
git clone https://github.com/jgraph/docker-drawio.git
cd docker-drawio.git/self-contained
```
2. Configure `DRAWIO_LIGHTBOX_URL ` parameter in `self-contained/docker-compose.yml`. I use same link as `DRAWIO_VIEWER_URL ` (need to be clarified in README how to properly configure these parameters to use self-hosted viewer instead of viewer.diagrams.net to avoid manually adding **lightbox=1&** in generated URL)
3. run with --no-start, get docker-entrypoint.sh file from container
```shell
docker-compose up --no-start
docker cp self-contained_drawio_1:/docker-entrypoint.sh docker-entrypoint.sh
```
4. modify **docker-entrypoint.sh** locally: add line with `DRAWIO_LIGHTBOX_URL` near line 33:
```shell
...
#DRAWIO_VIEWER_URL is path to the viewer js, e.g. https://www.example.com/js/viewer.min.js
echo "window.DRAWIO_VIEWER_URL = '${DRAWIO_VIEWER_URL}';" >> $CATALINA_HOME/webapps/draw/js/PreConfig.js
echo "window.DRAWIO_LIGHTBOX_URL = '${DRAWIO_LIGHTBOX_URL}';" >> $CATALINA_HOME/webapps/draw/js/PreConfig.js
echo "window.DRAW_MATH_URL = 'math';" >> $CATALINA_HOME/webapps/draw/js/PreConfig.js
...
```
5. Write back **docker-entrypoint.sh** to drawio container and start it
```shell
docker cp docker-entrypoint.sh self-contained_drawio_1:/docker-entrypoint.sh 
docker-compose start
```
6. If you want to use Lightbox viewer for exported URL then modify manually generated URL by adding **lightbox=1&** as follows
Menu --> Export As --> URL --> Create  
 * Example of generated link:   
`https://drawio.local.instance.com/?highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram1.drawio#blablablablabla....`
 * Add **lightbox=1&** after `?` in generated link:
`https://drawio.local.instance.com/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram1.drawio#blablablablabla....`

**Comment by rootnoir** [comment] 2021-03-03 12:03
> URL link is not properly generated when doing File-->Export to-->URL. Currently this link opens file in editor even if lightbox tick is chosen on URL creation dialog. Need to manually edit generated URL by adding lightbox=1&.

Seems to me, the problem is in this section..
https://github.com/jgraph/drawio/blob/ff20bcd476b55b37a9f705e83e0db39aa6847e8e/src/main/webapp/js/diagramly/EditorUi.js#L5156
IMHO, if (lightbox) will return "params.push('lightbox=1')" every time, when True.. not only when "urlParams['dev'] == '1'"

**Comment by rootnoir** [comment] 2021-03-04 10:18
Solution: https://github.com/jgraph/drawio/issues/1855#issuecomment-790499581

**Comment by davidjgraph** [comment] 2022-01-06 11:44
Fixed in https://github.com/jgraph/drawio/issues/1855

**Closed by davidjgraph** 2022-01-06 11:44 UTC
